src/category/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<sub_category>/', views.category_items )
]

src/core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.core_view),
    path('about/', views.core_about, name='about'),
    path('signin/', views.core_signin, name='signin'),
    path('signup/', views.core_signup, name='signup'),
]

src/freshcart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('<category>/', include('category.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title_category = models.CharField(max_length=255)
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title_category

class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    title_subcategory = models.CharField(max_length=255, verbose_name="Nom")
    class Meta:
        verbose_name_plural = 'Subcategories'

    def __str__(self):
        return self.title_subcategory


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory,related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.FloatField()
    image = models.ImageField(upload_to='items_image', blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'{self.name} {self.price}'

src/core/models.py
from django.db import models

# Create your models here.

src/category/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound

# Create your views here.
from . import models


def category_items(request, category, sub_category):
    if category == 'food':

        match sub_category:
            case 'bakery':
                sub_category_name = models.SubCategory.objects.get(id=1)
                sub_category_products = models.Product.objects.filter(subcategory=1)
                context = {'name': sub_category_name, 'list': sub_category_products }
            case 'desserts':
                sub_category_name = models.SubCategory.objects.get(id=1)
                sub_category_products = models.Product.objects.filter(subcategory=2)
                context = {'name': sub_category_name, 'list': sub_category_products }
            case 'drinks':
                sub_category_name = models.SubCategory.objects.get(id=1)
                sub_category_products = models.Product.objects.filter(subcategory=3)
                context = {'name': sub_category_name, 'list': sub_category_products}
            case default:
                return HttpResponseNotFound("Sub_category not found. CAll us and we create it...")
        return render(request, 'category/index.html', context)

    return HttpResponseNotFound("Category not found")

src/core/views.py
from django.shortcuts import render


# Create your views here.
def core_view(request):
    return render(request, 'core/index.html', {})


def core_signin(request):
    return render(request, 'core/signin.html', {})


def core_signup(request):
    return render(request, 'core/signup.html', {})


def core_about(request):
    return render(request, 'core/about.html', {})

src/category/templates/category/index.html
{% extends 'core/base.html' %}

{% block title %}{{  name }} {% endblock %}

{% block content%}
<div>

    {% for i in list %}
    <p> {{ i.name }} </p>
    <p> {{ i.price }} </p>
    {% if i.image %}
        <img src="{{ i.image.url }}" alt="image">
    {% endif %}
    {% endfor %}
</div>
{%endblock%}

src/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title%}About{% endblock %}

{% block content %}
<h2>About</h2>
<p>Phone + 375 25 111 11 11</p>
<address>Address: Minsk</address>
{% endblock%}

src/core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Welcome{% endblock %}</title>
</head>
<body>
    {% include 'core/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'core/footer.html' %}
</body>
</html>

src/core/templates/core/footer.html
<h1>Footer</h1>

src/core/templates/core/header.html
<h1>Freshcart</h1>
<h2>Header block</h2>
{% include 'core/nav.html' %}

src/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Index{% endblock %}

{% block content %}Index{% endblock %}

src/core/templates/core/nav.html
<nav>
    <p>food -> bakery/dessers/drinks</p>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'core:about' %}">About</a></li>
        <li><a href="{% url 'core:signup' %}">Signup</a></li>
        <li><a href="{% url 'core:signin' %}">Sign in</a></li>
        <li><a href="/food/bakery">bakery</a></li>
        <li><a href="/food/desserts">desserts</a></li>
        <li><a href="/food/drinks">drinks</a></li>
    </ul>
</nav>

src/core/templates/core/signin.html
{% extends 'core/base.html' %}

{% block content%}
<div>Sign in</div>
{% endblock %}

src/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block content%}
<div>Signup</div>
{% endblock %}